table Films
	lineageTag: 5b4b4d2a-6116-446b-90d5-f9930d416d07

	measure 'Total Box Office' = SUM(Films[WorldwideBoxOffice])
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: 7a94550b-745e-4047-b730-59003896670c

	measure 'Film Count' = COUNTROWS(Films)
		formatString: 0
		lineageTag: eacfde74-8977-483f-90d9-85a3331ee2d5

	measure 'Avg RT Score' = AVERAGE(Films[RTCriticScore])
		formatString: 0\%
		lineageTag: f3ab9531-016b-4e86-8e13-014688ae1b51

	measure PhaseYearLabel = SELECTEDVALUE(Films[Phase]) & " · " & FORMAT(SELECTEDVALUE(Films[ReleaseDate]), "yyyy")
		lineageTag: a1c2e3f4-1111-2222-3333-444455556666

	measure 'Budget Sum' = SUM(Films[Budget])
		formatString: \$#,0,,.0"M"
		lineageTag: b2d3f4a5-1111-2222-3333-444455556666

	measure 'Audience Score' = AVERAGE(Films[RTAudienceScore])
		formatString: 0\%
		lineageTag: c3e4a5b6-1111-2222-3333-444455556666

	measure 'Runtime Director' = SUM(Films[RuntimeMinutes]) & " min · " & SELECTEDVALUE(Films[Director])
		lineageTag: d4f5b6c7-1111-2222-3333-444455556666

	measure 'Top Grosser' =
			
			MAXX(
			    TOPN(1, ALL(Films), [Total Box Office], DESC),
			    Films[Title]
			)
		lineageTag: 3cec8c72-00c8-4b29-848f-5681a0a8b3c4

	column Title
		dataType: string
		lineageTag: c22c6d7e-3606-4ed1-8c4b-3a0faa909f88
		summarizeBy: none
		sourceColumn: Title

	column 'Title Short' =
			VAR _t = Films[Title]
			VAR _colon = FIND(":", _t, 1, 0)
			RETURN
			    IF(_colon = 0, _t, TRIM(MID(_t, _colon + 1, 999)))
		dataType: string
		lineageTag: 8e9f0a1b-2c3d-4e5f-6071-829304a5b6c7
		summarizeBy: none

	column Phase
		dataType: string
		lineageTag: 62f1741b-22b7-4c1e-b2a3-4f2fa9b2693a
		summarizeBy: none
		sourceColumn: Phase

	column ReleaseDate
		dataType: dateTime
		formatString: Long Date
		lineageTag: c64c5379-7d60-431e-9c10-f49c72f98f84
		summarizeBy: none
		sourceColumn: ReleaseDate

		annotation UnderlyingDateTimeDataType = Date

	column WorldwideBoxOffice
		dataType: int64
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: d9890d6d-0fef-4f5e-825d-79a41a480a83
		summarizeBy: sum
		sourceColumn: WorldwideBoxOffice

	column Budget
		dataType: int64
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: b02a3b35-0b42-4974-a7cc-901951bf620b
		summarizeBy: sum
		sourceColumn: Budget

	column RTCriticScore
		dataType: int64
		formatString: 0
		lineageTag: 968ef0c2-e12f-4ae0-88b1-10756604add4
		summarizeBy: average
		sourceColumn: RTCriticScore

	column RTAudienceScore
		dataType: int64
		formatString: 0
		lineageTag: 4db6384c-99c2-4259-afa3-958e626111cb
		summarizeBy: average
		sourceColumn: RTAudienceScore

	column Director
		dataType: string
		lineageTag: f3920359-8ad9-483b-9a7f-842de2c2625a
		summarizeBy: none
		sourceColumn: Director

	column RuntimeMinutes
		dataType: int64
		formatString: 0
		lineageTag: 22d02c15-fb9b-4e4d-aad9-666c5adb924a
		summarizeBy: sum
		sourceColumn: RuntimeMinutes

	column PosterUrl
		dataType: string
		lineageTag: 4756a7ea-4a20-4ff3-9513-bc9fc5594eca
		dataCategory: ImageUrl
		summarizeBy: none
		sourceColumn: PosterUrl

	partition Films = m
		mode: import
		source =
				let
				    Source = Csv.Document(
				        File.Contents("C:\Users\jmanw\claude projects\miniviz-week3\Data\mcu_films.csv"),
				        [Delimiter=",", Columns=10, Encoding=65001, QuoteStyle=QuoteStyle.Csv]
				    ),
				    PromoteHeaders = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    ChangeTypes = Table.TransformColumnTypes(PromoteHeaders, {
				        {"Title", type text},
				        {"Phase", type text},
				        {"ReleaseDate", type date},
				        {"WorldwideBoxOffice", Int64.Type},
				        {"Budget", Int64.Type},
				        {"RTCriticScore", Int64.Type},
				        {"RTAudienceScore", Int64.Type},
				        {"Director", type text},
				        {"RuntimeMinutes", Int64.Type},
				        {"PosterUrl", type text}
				    })
				in
				    ChangeTypes

